$(document).ready(function(){
  $.post(
    "https://infodb.iutmetz.univ-lorraine.fr/~zingraff7u/Cordova/PHP/Nom.php",
    function(data){
      if(data!=""){
          $("#profil").html(data);
      }
    }
  );
});
